/**
 * Candidate Lambdapi probe serialization for checked LF definitions.
 *
 * Transparent definitions are emitted with their checked bodies. Opaque
 * definitions are emitted as body-free symbols, matching the TypeScript
 * conversion boundary rather than leaking their stored implementation.
 */

import {
    formatSourceSpan
} from './kernel';
import {
    KernelSerializationOptions,
    LAMBDAPI_V32_MODULE,
    serializeKernelExpression
} from './lambdapi';
import {
    CoreLfDeclarationEnvironment
} from './lf_declarations';
import {
    KernelProbeAssertion,
    KernelProbeConversionAssertion,
    ProbeSourceMapEntry,
    SerializedProbe
} from './probe';

export interface CoreLfKernelProbe {
    readonly environment: CoreLfDeclarationEnvironment;
    readonly assertions: readonly KernelProbeAssertion[];
    readonly conversions?: readonly KernelProbeConversionAssertion[];
    /**
     * Reviewed opaque primitive declarations imported from the active
     * Lambdapi module. They remain present for TypeScript checking but are
     * omitted as local declarations and remapped only during serialization.
     */
    readonly externalFreeReferences?: KernelSerializationOptions[
        'externalFreeReferences'
    ];
}

const safeCommentText = (value: string): string =>
    value.replace(/[\r\n]+/g, ' ').replace(/\*\//g, '* /');

export function serializeCoreLfKernelProbe(
    probe: CoreLfKernelProbe
): SerializedProbe {
    const lines: string[] = [];
    const sourceMap: ProbeSourceMapEntry[] = [];
    const conversions = probe.conversions ?? [];
    const externalFreeReferences = probe.externalFreeReferences ?? {};
    const externalNames = new Set(
        Object.entries(externalFreeReferences)
            .filter((entry): entry is [string, string] =>
                entry[1] !== undefined
            )
            .map(([name]) => name)
    );
    for (const name of externalNames) {
        const declaration = probe.environment.lookup(name);
        if (!declaration) {
            throw new Error(
                `External Core LF reference '${name}' has no checked ` +
                'declaration'
            );
        }
        if (
            declaration.body !== undefined ||
            declaration.transparency !== 'opaque'
        ) {
            throw new Error(
                `External Core LF reference '${name}' must be an opaque ` +
                'body-free declaration'
            );
        }
    }
    const serialize = (expression: Parameters<
        typeof serializeKernelExpression
    >[0]): string => serializeKernelExpression(expression, {
        externalFreeReferences
    });
    const push = (line: string): number => {
        lines.push(line);
        return lines.length;
    };

    push('/* Generated by the TypeScript emdash v3.2 Core LF probe. */');
    push(`require open ${LAMBDAPI_V32_MODULE};`);
    push('');

    const emittedDeclarations = probe.environment.declarations.filter(
        declaration => !externalNames.has(declaration.name)
    );
    for (const declaration of emittedDeclarations) {
        const span = declaration.provenance.span;
        if (!span) {
            throw new Error(
                `Core LF probe declaration '${declaration.name}' has no ` +
                'source span'
            );
        }
        push(`// source ${formatSourceSpan(span)}`);
        const type = serialize(declaration.type);
        const body = declaration.transparency === 'transparent' &&
            declaration.body !== undefined
            ? ` ≔ ${serialize(declaration.body)}`
            : '';
        const generatedLine = push(
            `symbol ${declaration.name} : ${type}${body};`
        );
        sourceMap.push({
            generatedLine,
            kind: 'declaration',
            label: declaration.name,
            sourceSpan: span
        });
    }

    if (
        emittedDeclarations.length > 0 &&
        (probe.assertions.length > 0 || conversions.length > 0)
    ) {
        push('');
    }

    for (const assertion of probe.assertions) {
        push(
            `// ${safeCommentText(assertion.label)}; source ` +
            formatSourceSpan(assertion.span)
        );
        const generatedLine = push(
            `assert ⊢ ${serialize(assertion.term)} : ` +
            `${serialize(assertion.type)};`
        );
        sourceMap.push({
            generatedLine,
            kind: 'assertion',
            label: assertion.label,
            sourceSpan: assertion.span
        });
    }

    if (probe.assertions.length > 0 && conversions.length > 0) {
        push('');
    }

    for (const conversion of conversions) {
        push(
            `// ${safeCommentText(conversion.label)}; source ` +
            formatSourceSpan(conversion.span)
        );
        const generatedLine = push(
            `assert ⊢ ${serialize(conversion.left)} ≡ ` +
            `${serialize(conversion.right)};`
        );
        sourceMap.push({
            generatedLine,
            kind: 'conversion',
            label: conversion.label,
            sourceSpan: conversion.span
        });
    }

    return {
        source: `${lines.join('\n')}\n`,
        sourceMap: Object.freeze(sourceMap.map(entry =>
            Object.freeze({ ...entry })
        ))
    };
}
