/**
 * Deterministic Lambdapi probe serialization and bounded checker bridge.
 */

import { spawnSync } from 'node:child_process';
import {
    existsSync,
    mkdirSync,
    mkdtempSync,
    rmSync,
    writeFileSync
} from 'node:fs';
import { join, relative, resolve } from 'node:path';
import {
    KernelExpression,
    SourceSpan,
    formatSourceSpan
} from './kernel';
import {
    LAMBDAPI_V32_MODULE,
    serializeKernelExpression
} from './lambdapi';
import {
    ElaboratedSurfaceTerm,
    elaborateSurfaceTerm
} from './elaborator';
import {
    SurfaceContext,
    SurfaceTerm,
    coreTypeToKernelType
} from './surface';

export interface KernelProbeDeclaration {
    name: string;
    type: KernelExpression;
    span: SourceSpan;
}

export interface KernelProbeAssertion {
    label: string;
    term: KernelExpression;
    type: KernelExpression;
    span: SourceSpan;
}

export interface KernelProbe {
    requiredModule: typeof LAMBDAPI_V32_MODULE;
    declarations: readonly KernelProbeDeclaration[];
    assertions: readonly KernelProbeAssertion[];
}

export interface ProbeSourceMapEntry {
    generatedLine: number;
    kind: 'declaration' | 'assertion';
    label: string;
    sourceSpan: SourceSpan;
}

export interface SerializedProbe {
    source: string;
    sourceMap: readonly ProbeSourceMapEntry[];
}

export interface SurfaceProbeCase {
    label: string;
    term: SurfaceTerm;
}

export interface CompiledSurfaceProbeCase extends SurfaceProbeCase {
    elaborated: ElaboratedSurfaceTerm;
}

export interface CompiledSurfaceProbe {
    cases: readonly CompiledSurfaceProbeCase[];
    probe: KernelProbe;
    serialized: SerializedProbe;
}

const safeCommentText = (value: string): string =>
    value.replace(/[\r\n]+/g, ' ').replace(/\*\//g, '* /');

export function declarationsFromSurfaceContext(
    context: SurfaceContext
): readonly KernelProbeDeclaration[] {
    return context.bindings.map(binding => ({
        name: binding.name,
        type: binding.kernelType,
        span: binding.span
    }));
}

export function compileSurfaceProbe(
    context: SurfaceContext,
    cases: readonly SurfaceProbeCase[]
): CompiledSurfaceProbe {
    const compiledCases = cases.map(testCase => ({
        ...testCase,
        elaborated: elaborateSurfaceTerm(context, testCase.term)
    }));
    const probe: KernelProbe = {
        requiredModule: LAMBDAPI_V32_MODULE,
        declarations: declarationsFromSurfaceContext(context),
        assertions: compiledCases.map(testCase => ({
            label: testCase.label,
            term: testCase.elaborated.term,
            type: coreTypeToKernelType(
                testCase.elaborated.type,
                testCase.elaborated.sourceSpan,
                `expected type of probe assertion ${testCase.label}`
            ),
            span: testCase.elaborated.sourceSpan
        }))
    };
    return {
        cases: compiledCases,
        probe,
        serialized: serializeKernelProbe(probe)
    };
}

export function serializeKernelProbe(probe: KernelProbe): SerializedProbe {
    const lines: string[] = [];
    const sourceMap: ProbeSourceMapEntry[] = [];

    const push = (line: string): number => {
        lines.push(line);
        return lines.length;
    };

    push('/* Generated by the TypeScript emdash v3.2 ELAB-0 probe slice. */');
    push(`require open ${probe.requiredModule};`);
    push('');

    for (const declaration of probe.declarations) {
        push(`// source ${formatSourceSpan(declaration.span)}`);
        const generatedLine = push(
            `symbol ${declaration.name} : ` +
            `${serializeKernelExpression(declaration.type)};`
        );
        sourceMap.push({
            generatedLine,
            kind: 'declaration',
            label: declaration.name,
            sourceSpan: declaration.span
        });
    }

    if (probe.declarations.length > 0 && probe.assertions.length > 0) {
        push('');
    }

    for (const assertion of probe.assertions) {
        push(
            `// ${safeCommentText(assertion.label)}; source ` +
            formatSourceSpan(assertion.span)
        );
        const generatedLine = push(
            `assert ⊢ ${serializeKernelExpression(assertion.term)} : ` +
            `${serializeKernelExpression(assertion.type)};`
        );
        sourceMap.push({
            generatedLine,
            kind: 'assertion',
            label: assertion.label,
            sourceSpan: assertion.span
        });
    }

    return {
        source: `${lines.join('\n')}\n`,
        sourceMap
    };
}

export interface LambdapiProbeOptions {
    /**
     * Directory containing lambdapi.pkg and the active emdash3_2.lp module.
     */
    packageRoot: string;
    /**
     * Hard upper bound. Repository policy forbids exploratory checks over 60s.
     */
    timeoutMs?: number;
}

export interface LambdapiProbeResult {
    accepted: boolean;
    timedOut: boolean;
    status: number | null;
    signal: NodeJS.Signals | null;
    stdout: string;
    stderr: string;
    diagnostics: string;
}

export function checkLambdapiProbe(
    serialized: SerializedProbe,
    options: LambdapiProbeOptions
): LambdapiProbeResult {
    const timeoutMs = options.timeoutMs ?? 30_000;
    if (!Number.isInteger(timeoutMs) || timeoutMs <= 0 || timeoutMs > 60_000) {
        throw new Error(
            `Lambdapi probe timeout must be an integer in 1..60000ms; ` +
            `received ${timeoutMs}`
        );
    }

    const packageRoot = resolve(options.packageRoot);
    if (!existsSync(join(packageRoot, 'lambdapi.pkg'))) {
        throw new Error(
            `Lambdapi package root has no lambdapi.pkg: ${packageRoot}`
        );
    }

    const temporaryRoot = join(packageRoot, 'tmp');
    mkdirSync(temporaryRoot, { recursive: true });
    const temporaryDirectory = mkdtempSync(join(temporaryRoot, 'elab0-'));
    const probePath = join(temporaryDirectory, 'probe.lp');

    try {
        writeFileSync(probePath, serialized.source, 'utf8');
        const result = spawnSync(
            'lambdapi',
            ['check', '-w', relative(packageRoot, probePath)],
            {
                cwd: packageRoot,
                encoding: 'utf8',
                timeout: timeoutMs,
                killSignal: 'SIGINT'
            }
        );
        const stdout = result.stdout ?? '';
        const stderr = result.stderr ?? '';
        const errorCode = (result.error as NodeJS.ErrnoException | undefined)
            ?.code;
        const timedOut = errorCode === 'ETIMEDOUT';
        const errorText = result.error
            ? `${result.error.name}: ${result.error.message}`
            : '';
        const diagnostics = [stdout, stderr, errorText]
            .filter(part => part.length > 0)
            .join('\n');

        return {
            accepted: result.status === 0 && !result.error,
            timedOut,
            status: result.status,
            signal: result.signal,
            stdout,
            stderr,
            diagnostics
        };
    } finally {
        rmSync(temporaryDirectory, { recursive: true, force: true });
    }
}
