// Check exactness with its actual declaration dependencies, preserving their terms.
import { freydProbeDependencies } from './v3_2_algebra_formal_freyd_probe_dependencies';
import { CoreLfDeclarationEnvironment } from '../src/v3_2/lf_declarations';
import { serializeCoreLfKernelProbe } from '../src/v3_2/lf_probe';
import { FREYD_NATIVE_MODEL_PROBE_BINDINGS } from './v3_2_algebra_formal_freyd_native_model_fixtures';
import { FORMAL_FREYD_NATIVE_LES_CERTIFICATE_SIGNATURE_BINDINGS } from '../src/v3_2/algebra_formal_freyd_native_les_certificate_signatures';

/** Import owner shared by fresh emission and exact-body replay of saved artifacts. */
export const FREYD_NATIVE_LES_CERTIFICATE_PROBE_IMPORTS = [
    'emdash3_2_commutative_algebra_freyd_chain_map_introduction',
    'emdash3_2_commutative_algebra_freyd_adjunction_model_arrows',
    'emdash3_2_commutative_algebra_freyd_adjunction_model_connecting_observation',
    'emdash3_2_commutative_algebra_freyd_observation_endpoints',
    'emdash3_2_commutative_algebra_freyd_native_les_certificate_views'
].map(name => 'require open emdash.' + name + ';').join('\n');

export function freydNativeLesCertificateImportHeader(source: string): string {
    const marker = '/* Generated by the TypeScript emdash v3.2 Core LF probe. */\n';
    if (!source.startsWith(marker)) throw new Error('Use an emitted Core LF probe for certificate imports');
    const rest = source.slice(marker.length);
    const header = /^(?:require open emdash\.[A-Za-z0-9_.]+;\n)+/.exec(rest);
    if (!header) throw new Error('Missing emitted probe imports');
    return marker + FREYD_NATIVE_LES_CERTIFICATE_PROBE_IMPORTS + '\n' + rest.slice(header[0].length);
}

function exactnessClosure(environment: CoreLfDeclarationEnvironment,
    assertions: Parameters<typeof serializeCoreLfKernelProbe>[0]['assertions'], allowDefinitions: boolean,
    externalBindings: Readonly<Record<string, string>> = FREYD_NATIVE_MODEL_PROBE_BINDINGS) {
    const { selected, count } = freydProbeDependencies(environment, assertions, allowDefinitions);
    const bindings = Object.fromEntries(Object.entries(externalBindings).filter(([name]) => selected.lookup(name)));
    return { selected, bindings, count };
}

export function freydNativeExactnessProbe(environment: CoreLfDeclarationEnvironment,
    assertions: Parameters<typeof serializeCoreLfKernelProbe>[0]['assertions']) {
    const { selected, bindings, count } = exactnessClosure(environment, assertions, false);
    const source = serializeCoreLfKernelProbe({ environment: selected, assertions, externalFreeReferences: bindings }).source.replace(
        'require open emdash.emdash3_2;',
        'require open emdash.emdash3_2_commutative_algebra_freyd_chain_map_introduction;\n' +
        'require open emdash.emdash3_2_commutative_algebra_freyd_adjunction_model_exactness_observations;');
    return { environment: selected, source, declarations: count };
}

/** The point-data owner is checked before the concrete matrix inputs. */
export function freydNativeExactnessPointProbe(environment: CoreLfDeclarationEnvironment,
    assertions: Parameters<typeof serializeCoreLfKernelProbe>[0]['assertions']) {
    const { selected, bindings, count } = exactnessClosure(environment, assertions, true);
    const source = serializeCoreLfKernelProbe({ environment: selected, assertions, externalFreeReferences: bindings }).source.replace(
        'require open emdash.emdash3_2;',
        'require open emdash.emdash3_2_commutative_algebra_freyd_adjunction_model_point_exactness;\n' +
        'require open emdash.emdash3_2_commutative_algebra_freyd_chain_map_introduction;');
    return { environment: selected, source, declarations: count };
}

/** Check the finite certificate's actual owners, retaining exactly the required declarations. */
export function freydNativeLesCertificateProbe(environment: CoreLfDeclarationEnvironment,
    assertions: Parameters<typeof serializeCoreLfKernelProbe>[0]['assertions']) {
    const { selected, bindings, count } = exactnessClosure(environment, assertions, true,
        { ...FREYD_NATIVE_MODEL_PROBE_BINDINGS, ...FORMAL_FREYD_NATIVE_LES_CERTIFICATE_SIGNATURE_BINDINGS });
    const source = freydNativeLesCertificateImportHeader(
        serializeCoreLfKernelProbe({ environment: selected, assertions, externalFreeReferences: bindings }).source);
    return { environment: selected, source, declarations: count };
}
