#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

# During early development, a “hung” typecheck usually indicates a
# rewrite/unification issue. Use one measured per-target ceiling for focused
# and registered checks so near-boundary valid terms are classified uniformly.
: "${EMDASH_TYPECHECK_TIMEOUT:=90s}"
: "${EMDASH_LAMBDAPI_WARNINGS:=0}"

warning_flags=(-w)
case "$EMDASH_LAMBDAPI_WARNINGS" in
  1|true|TRUE|yes|YES|on|ON)
    warning_flags=()
    ;;
  0|false|FALSE|no|NO|off|OFF)
    ;;
  *)
    printf 'invalid EMDASH_LAMBDAPI_WARNINGS value: %s\n' "$EMDASH_LAMBDAPI_WARNINGS" >&2
    exit 2
    ;;
esac

extra_flags=()
if [[ -n "${EMDASH_LAMBDAPI_FLAGS:-}" ]]; then
  read -r -a extra_flags <<< "$EMDASH_LAMBDAPI_FLAGS"
fi

six_term_join_checked=0
normalization_join_checked=0
snake_rows_join_checked=0
snake_target_cycles_join_checked=0
snake_target_homology_join_checked=0
snake_source_boundary_join_checked=0
homology_connecting_join_checked=0
homology_exact_window_join_checked=0
homology_window_families_join_checked=0
homology_arrow_tails_join_checked=0

is_abelian_snake_six_term_join() {
  case "$1" in
    emdash3_2_abelian_snake_six_term_inner_kernel_u_zero_foundation.lp|\
    emdash3_2_abelian_snake_six_term_inner_kernel_q2_zero_foundation.lp|\
    emdash3_2_abelian_snake_six_term_inner_kernel_zero.lp|\
    emdash3_2_abelian_snake_six_term_inner_cokernel_p1_zero_foundation.lp|\
    emdash3_2_abelian_snake_six_term_inner_cokernel_zero.lp|\
    emdash3_2_abelian_snake_six_term_result.lp|\
    emdash3_2_abelian_snake_six_term_result_projections.lp|\
    emdash3_2_exactness_covers_foundation.lp|\
    emdash3_2_exactness_covers.lp|\
    emdash3_2_exactness_covers_from_exact.lp|\
    emdash3_2_abelian_canonical_kernel_exactness.lp|\
    emdash3_2_abelian_canonical_cokernel_foundation.lp|\
    emdash3_2_abelian_canonical_cokernel_factor.lp|\
    emdash3_2_abelian_canonical_cokernel_epic.lp|\
    emdash3_2_abelian_canonical_cokernel_exactness.lp|\
    emdash3_2_abelian_canonical_cokernel_covers.lp|\
    emdash3_2_abelian_snake_exact_first_foundation.lp|\
    emdash3_2_abelian_snake_exact_first_row_cover_projections.lp|\
    emdash3_2_abelian_snake_exact_first_alpha_zero.lp|\
    emdash3_2_abelian_snake_exact_first_factor.lp|\
    emdash3_2_abelian_snake_exact_first_comparison.lp|\
    emdash3_2_abelian_snake_exact_first_result.lp|\
    emdash3_2_preadditive_difference_paths.lp|\
    emdash3_2_abelian_snake_exact_second_*.lp|\
    emdash3_2_exactness_extensions*.lp|\
    emdash3_2_abelian_canonical_kernel_extensions*.lp|\
    emdash3_2_abelian_snake_exact_third_*.lp|\
    emdash3_2_abelian_snake_six_term_exact_*.lp|\
    emdash3_2_abelian_snake_six_term_canonical_exactness.lp)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

check_file() {
  local file="$1"
  case "$file" in
    emdash3_2_finite_arrow_tails.lp|\
    emdash3_2_finite_arrow_tail_append.lp|\
    emdash3_2_computational_exact_arrow_tails.lp)
      if [[ "$homology_arrow_tails_join_checked" -eq 0 ]]; then
        ./scripts/check_homology_arrow_tails.sh
        homology_arrow_tails_join_checked=1
      fi
      return ;;
    emdash3_2_short_exact_row_families.lp|\
    emdash3_2_homology_window_families.lp|\
    emdash3_2_homology_window_columns.lp|\
    emdash3_2_homology_window_column_usability.lp|\
    emdash3_2_homology_window_connecting_transformation.lp)
      if [[ "$homology_window_families_join_checked" -eq 0 ]]; then
        ./scripts/check_homology_window_families.sh
        homology_window_families_join_checked=1
      fi
      return ;;
    emdash3_2_homology_exact_window.lp|\
    emdash3_2_homology_exact_window_result.lp)
      if [[ "$homology_exact_window_join_checked" -eq 0 ]]; then
        ./scripts/check_homology_exact_window.sh
        homology_exact_window_join_checked=1
      fi
      return ;;
    emdash3_2_homology_connecting_factor.lp|\
    emdash3_2_homology_connecting.lp)
      if [[ "$homology_connecting_join_checked" -eq 0 ]]; then
        ./scripts/check_homology_connecting.sh
        homology_connecting_join_checked=1
      fi
      return ;;
    emdash3_2_snake_row_source_second_comparison.lp|\
    emdash3_2_snake_row_source_boundary_covered.lp|\
    emdash3_2_snake_row_source_boundary_zero.lp)
      if [[ "$snake_source_boundary_join_checked" -eq 0 ]]; then
        ./scripts/check_snake_row_source_boundary.sh
        snake_source_boundary_join_checked=1
      fi
      return ;;
    emdash3_2_snake_row_target_cokernel_projection.lp|\
    emdash3_2_snake_row_target_homology_normal.lp|\
    emdash3_2_snake_row_target_homology_factor.lp)
      if [[ "$snake_target_homology_join_checked" -eq 0 ]]; then
        ./scripts/check_snake_row_target_homology.sh
        snake_target_homology_join_checked=1
      fi
      return ;;
    emdash3_2_chain_pair_map_cycle_lifts.lp|\
    emdash3_2_hom_factor_source_isos.lp|\
    emdash3_2_short_exact_row_chain_columns.lp|\
    emdash3_2_snake_row_target_factors.lp|\
    emdash3_2_snake_row_target_cycles.lp)
      if [[ "$snake_target_cycles_join_checked" -eq 0 ]]; then
        ./scripts/check_snake_row_target_cycles.sh
        snake_target_cycles_join_checked=1
      fi
      return ;;
    emdash3_2_chain_pair_map_snake.lp|\
    emdash3_2_snake_row_comparisons.lp|\
    emdash3_2_kernel_domain_comparison.lp|\
    emdash3_2_cokernel_codomain_comparison.lp|\
    emdash3_2_snake_row_source_cycle_iso.lp|\
    emdash3_2_snake_row_target_cokernel_iso.lp|\
    emdash3_2_abelian_structure_elimination.lp|\
    emdash3_2_abelian_snake_row_comparisons.lp|\
    emdash3_2_short_exact_row_snake.lp)
      if [[ "$snake_rows_join_checked" -eq 0 ]]; then
        ./scripts/check_snake_row_comparisons.sh
        snake_rows_join_checked=1
      fi
      return ;;
    emdash3_2_short_exact_rows.lp|\
    emdash3_2_kernel_short_exact_rows.lp|\
    emdash3_2_selected_short_exact_rows.lp|\
    emdash3_2_monic_image_comparison.lp|\
    emdash3_2_short_exact_row_comparison_fibres.lp|\
    emdash3_2_monic_selected_row_comparison.lp|\
    emdash3_2_short_exact_normalization_foundation.lp|\
    emdash3_2_short_exact_normalization_isos.lp|\
    emdash3_2_short_exact_normalization_projections.lp|\
    emdash3_2_short_exact_normalization.lp)
      if [[ "$normalization_join_checked" -eq 0 ]]; then
        ./scripts/check_short_exact_normalization.sh
        normalization_join_checked=1
      fi
      return ;;
  esac
  if is_abelian_snake_six_term_join "$file"; then
    if [[ "$six_term_join_checked" -eq 0 ]]; then
      ./scripts/check_abelian_snake_six_term.sh
      six_term_join_checked=1
    fi
    return
  fi
  if command -v timeout >/dev/null 2>&1; then
    timeout --signal=INT "$EMDASH_TYPECHECK_TIMEOUT" \
      lambdapi check "${warning_flags[@]}" "${extra_flags[@]}" "$file"
  else
    lambdapi check "${warning_flags[@]}" "${extra_flags[@]}" "$file"
  fi
}

files=("$@")
if [[ ${#files[@]} -eq 0 ]]; then
  files=(emdash3_2.lp emdash3_2_preadditive_categories.lp emdash3_2_presheaves.lp emdash3_2_fibrewise_sigma.lp emdash3_2_nat_arithmetic.lp emdash3_2_finite_families.lp emdash3_2_commutative_algebra.lp emdash3_2_commutative_algebra_derived_laws.lp emdash3_2_commutative_algebra_category.lp emdash3_2_commutative_algebra_product.lp emdash3_2_commutative_algebra_f2.lp emdash3_2_commutative_algebra_finite.lp emdash3_2_commutative_algebra_finite_modules.lp emdash3_2_commutative_algebra_presentations.lp emdash3_2_commutative_algebra_bounded_free_complexes.lp emdash3_2_commutative_algebra_bounded_free_chain_maps.lp emdash3_2_commutative_algebra_finite_free_category.lp emdash3_2_commutative_algebra_presentation_operations.lp emdash3_2_commutative_algebra_matrix_additive_laws.lp emdash3_2_commutative_algebra_matrix_subtractive_laws.lp emdash3_2_commutative_algebra_presentation_additive_operations.lp emdash3_2_commutative_algebra_presentation_subtractive_operations.lp emdash3_2_commutative_algebra_presentation_agreement_operations.lp emdash3_2_commutative_algebra_freyd_presentations.lp emdash3_2_commutative_algebra_freyd_operations.lp emdash3_2_commutative_algebra_freyd_usability.lp emdash3_2_commutative_algebra_freyd_preadditive_class_laws.lp emdash3_2_commutative_algebra_freyd_preadditive_laws.lp emdash3_2_commutative_algebra_freyd_preadditive.lp emdash3_2_commutative_algebra_polynomial.lp emdash3_2_commutative_algebra_localization.lp emdash3_2_commutative_algebra_localization_unit.lp emdash3_2_commutative_algebra_localization_zero.lp emdash3_2_commutative_algebra_localization_idempotent.lp emdash3_2_commutative_algebra_localization_comparison.lp emdash3_2_commutative_algebra_localization_overlap.lp emdash3_2_commutative_algebra_presheaves.lp emdash3_2_walking_end_hit.lp emdash3_2_eq1_hom_action.lp emdash3_2_eq1_evidence_property.lp emdash3_2_telescope_localization_hit.lp emdash3_2_integer_localization.lp emdash3_2_circle_hit.lp emdash3_2_groupoidal_interval_hit.lp emdash3_2_walking_interval_comparison.lp emdash3_2_walking_interval_restriction.lp emdash3_2_walking_interval_extension.lp emdash3_2_walking_interval_universality.lp emdash3_2_walking_circle_completion.lp emdash3_2_walking_circle_restriction.lp emdash3_2_walking_circle_extension.lp emdash3_2_walking_circle_universality.lp emdash3_2_walking_circle_monodromy.lp emdash3_2_groupoidal_closure.lp emdash3_2_path_pseudo_laxity.lp emdash3_2_gray_profiles.lp emdash3_2_walking_arrow.lp emdash3_2_gray_right_closure.lp emdash3_2_gray_walking_square.lp emdash3_2_gray_interchanger.lp emdash3_2_truncation_reflector.lp emdash3_2_truncation_set_path_induction.lp emdash3_2_circle_connectedness.lp emdash3_2_sieves.lp emdash3_2_sites.lp emdash3_2_sieve_extensions.lp emdash3_2_generated_topologies.lp emdash3_2_ringed_sites.lp emdash3_2_site_basis.lp emdash3_2_commutative_algebra_ringed_space_covers.lp emdash3_2_commutative_algebra_binary_covers.lp emdash3_2_commutative_algebra_ringed_space_restrictions.lp emdash3_2_commutative_algebra_locality.lp emdash3_2_commutative_algebra_local_ringed_sites.lp emdash3_2_commutative_algebra_matching.lp emdash3_2_commutative_algebra_glue.lp emdash3_2_commutative_algebra_affine_glue.lp emdash3_2_commutative_algebra_zariski.lp emdash3_2_commutative_algebra_zariski_topology.lp emdash3_2_commutative_algebra_localization_split.lp emdash3_2_commutative_algebra_affine_spec.lp emdash3_2_commutative_algebra_affine_zariski.lp emdash3_2_commutative_algebra_affine_ringed_sites.lp emdash3_2_commutative_algebra_affine_locality.lp emdash3_2_commutative_algebra_affine_schemes.lp emdash3_2_commutative_algebra_affine_basis.lp emdash3_2_commutative_algebra_affine_cover_charts.lp emdash3_2_commutative_algebra_affine_cover_presentations.lp emdash3_2_commutative_algebra_affine_cover_refinements.lp emdash3_2_commutative_algebra_locally_ringed_space_presentations.lp emdash3_2_commutative_algebra_site_relative_schemes.lp emdash3_2_commutative_algebra_affine_points.lp emdash3_2_commutative_algebra_affine_intersections.lp emdash3_2_commutative_algebra_affine_atlas.lp)
  files+=(emdash3_2_diagram_evaluation.lp)
  files+=(emdash3_2_walking_arrow_introduction.lp)
  files+=(emdash3_2_arrow_diagram_families.lp)
  files+=(emdash3_2_zero_arrow_diagrams.lp)
  files+=(emdash3_2_strict_transfor_component_paths.lp)
  files+=(emdash3_2_kernel_adjunction_presentations.lp)
  files+=(emdash3_2_cokernel_adjunction_presentations.lp)
  files+=(emdash3_2_adjunction_mates.lp)
  files+=(emdash3_2_zero_arrow_universal_tests.lp)
  files+=(emdash3_2_kernel_adjunction_mates.lp)
  files+=(emdash3_2_cokernel_adjunction_mates.lp)
  files+=(emdash3_2_homology_families.lp)
  files+=(emdash3_2_homology_family_selected_views.lp)
  files+=(emdash3_2_zero_arrow_cones.lp)
  files+=(emdash3_2_one_cat_zero_cones.lp)
  files+=(emdash3_2_zero_arrow_cone_chain_pairs.lp)
  files+=(emdash3_2_zero_arrow_cone_homology.lp)
  files+=(emdash3_2_commutative_algebra_freyd_zero_cones.lp)
  files+=(emdash3_2_kernel_adjunction_unmates.lp)
  files+=(emdash3_2_kernel_adjunction_unmate_paths.lp)
  files+=(emdash3_2_chain_pair_zero_cones.lp)
  files+=(emdash3_2_chain_pair_zero_cone_comparisons.lp)
  files+=(emdash3_2_kernel_adjunction_records.lp)
  files+=(emdash3_2_cokernel_adjunction_records.lp)
  files+=(emdash3_2_homology_family_records.lp)
  files+=(emdash3_2_chain_pair_homology_records.lp)
  files+=(emdash3_2_commutative_algebra_freyd_zero_cone_inputs.lp)
  files+=(emdash3_2_one_cat_arrow_diagrams.lp)
  files+=(emdash3_2_chain_pair_diagram_maps.lp)
  files+=(emdash3_2_adjunction_untranspose_naturality.lp)
  files+=(emdash3_2_zero_arrow_cone_map_introduction.lp)
  files+=(emdash3_2_kernel_presentation_inclusion_properties.lp)
  files+=(emdash3_2_kernel_presentation_boundary_naturality.lp)
  files+=(emdash3_2_chain_pair_zero_cone_maps.lp)
  files+=(emdash3_2_commutative_algebra_freyd_zero_cone_maps.lp)
  files+=(emdash3_2_commutative_algebra_freyd_homology_models.lp)
  files+=(emdash3_2_commutative_algebra_freyd_homology_model_records.lp)
  files+=(emdash3_2_commutative_algebra_freyd_homology_model_connecting.lp)
  files+=(emdash3_2_commutative_algebra_freyd_homology_model_normality.lp)
  files+=(emdash3_2_commutative_algebra_freyd_chain_map_introduction.lp)
  files+=(emdash3_2_commutative_algebra_freyd_homology_model_maps.lp)
  files+=(emdash3_2_finite_family_sums.lp)
  files+=(emdash3_2_commutative_algebra_matrix_blocks.lp)
  files+=(emdash3_2_commutative_algebra_matrix_block_laws.lp)
  files+=(emdash3_2_commutative_algebra_matrix_zero_rows.lp)
  files+=(emdash3_2_commutative_algebra_finite_free_direct_sums.lp)
  files+=(emdash3_2_commutative_algebra_finite_free_preadditive.lp)
  files+=(emdash3_2_commutative_algebra_finite_free_binary_products.lp)
  files+=(emdash3_2_commutative_algebra_finite_free_terminal_zero.lp)
  files+=(emdash3_2_commutative_algebra_finite_free_cartesian.lp)
  files+=(emdash3_2_commutative_algebra_finite_free_additive.lp)
  files+=(emdash3_2_commutative_algebra_finite_free_weak_pullbacks.lp)
  files+=(emdash3_2_commutative_algebra_freyd_kernel_choices.lp)
  files+=(emdash3_2_commutative_algebra_presentation_direct_sums.lp)
  files+=(emdash3_2_commutative_algebra_presentation_direct_sum_agreements.lp)
  files+=(emdash3_2_commutative_algebra_freyd_direct_sums.lp)
  files+=(emdash3_2_commutative_algebra_freyd_binary_products.lp)
  files+=(emdash3_2_commutative_algebra_freyd_terminal_zero.lp)
  files+=(emdash3_2_commutative_algebra_freyd_cartesian.lp)
  files+=(emdash3_2_additive_categories.lp)
  files+=(emdash3_2_weak_kernels.lp)
  files+=(emdash3_2_computational_weak_pullbacks.lp)
  files+=(emdash3_2_computational_weak_pullback_compatibility.lp)
  files+=(emdash3_2_computational_weak_pullback_cones.lp)
  files+=(emdash3_2_kernels_cokernels.lp)
  files+=(emdash3_2_computational_fiber_products.lp)
  files+=(emdash3_2_computational_pushouts.lp)
  files+=(emdash3_2_computational_homology.lp)
  files+=(emdash3_2_short_exact_sequences.lp)
  files+=(emdash3_2_exactness_reindex.lp)
  files+=(emdash3_2_abelian_categories.lp)
  files+=(emdash3_2_abelian_fiber_pushout_stability.lp)
  files+=(emdash3_2_preabelian_bimorphism_lemmas.lp)
  files+=(emdash3_2_abelian_images.lp)
  files+=(emdash3_2_abelian_image_bimorphisms.lp)
  files+=(emdash3_2_abelian_snake_lemma.lp)
  files+=(emdash3_2_abelian_snake_six_term_kernel_beta_foundation.lp)
  files+=(emdash3_2_abelian_snake_six_term_kernels.lp)
  files+=(emdash3_2_abelian_snake_six_term_cokernel_beta_foundation.lp)
  files+=(emdash3_2_abelian_snake_six_term_cokernels.lp)
  files+=(emdash3_2_abelian_snake_six_term_kernel_zero_foundation.lp)
  files+=(emdash3_2_abelian_snake_six_term_kernel_zero.lp)
  files+=(emdash3_2_abelian_snake_six_term_cokernel_zero_foundation.lp)
  files+=(emdash3_2_abelian_snake_six_term_cokernel_zero.lp)
  files+=(emdash3_2_abelian_snake_six_term_inner_kernel_factor.lp)
  files+=(emdash3_2_abelian_snake_six_term_inner_cokernel_cofactor.lp)
  files+=(emdash3_2_abelian_snake_six_term_inner_cokernel_middle_zero_foundation.lp)
  files+=(emdash3_2_abelian_snake_normal_epi_foundation.lp)
  files+=(emdash3_2_abelian_snake_normal_epi.lp)
  files+=(emdash3_2_abelian_snake_normal_mono_foundation.lp)
  files+=(emdash3_2_abelian_snake_normal_mono_test_foundation.lp)
  files+=(emdash3_2_abelian_snake_connecting.lp)
  files+=(emdash3_2_abelian_snake_covered_reconstruction.lp)
  files+=(emdash3_2_abelian_snake_connecting_result.lp)
  files+=(emdash3_2_abelian_snake_six_term_inner_kernel_u_zero_foundation.lp)
  files+=(emdash3_2_abelian_snake_six_term_inner_kernel_q2_zero_foundation.lp)
  files+=(emdash3_2_abelian_snake_six_term_inner_kernel_zero.lp)
  files+=(emdash3_2_abelian_snake_six_term_inner_cokernel_p1_zero_foundation.lp)
  files+=(emdash3_2_abelian_snake_six_term_inner_cokernel_zero.lp)
  files+=(emdash3_2_abelian_snake_six_term_result.lp)
  files+=(emdash3_2_abelian_snake_six_term_result_projections.lp)
  files+=(emdash3_2_exactness_covers_foundation.lp)
  files+=(emdash3_2_exactness_covers.lp)
  files+=(emdash3_2_exactness_covers_from_exact.lp)
  files+=(emdash3_2_abelian_canonical_kernel_exactness.lp)
  files+=(emdash3_2_abelian_canonical_cokernel_foundation.lp)
  files+=(emdash3_2_abelian_canonical_cokernel_factor.lp)
  files+=(emdash3_2_abelian_canonical_cokernel_epic.lp)
  files+=(emdash3_2_abelian_canonical_cokernel_exactness.lp)
  files+=(emdash3_2_abelian_canonical_cokernel_covers.lp)
  files+=(emdash3_2_abelian_snake_exact_first_foundation.lp)
  files+=(emdash3_2_abelian_snake_exact_first_row_cover_projections.lp)
  files+=(emdash3_2_abelian_snake_exact_first_alpha_zero.lp)
  files+=(emdash3_2_abelian_snake_exact_first_factor.lp)
  files+=(emdash3_2_abelian_snake_exact_first_comparison.lp)
  files+=(emdash3_2_abelian_snake_exact_first_result.lp)
  files+=(emdash3_2_preadditive_difference_paths.lp)
  files+=(emdash3_2_abelian_snake_exact_second_pullback.lp)
  files+=(emdash3_2_abelian_snake_exact_second_xi.lp)
  files+=(emdash3_2_abelian_snake_exact_second_q2_pi.lp)
  files+=(emdash3_2_abelian_snake_exact_second_pi_zero.lp)
  files+=(emdash3_2_abelian_snake_exact_second_alpha_cover_foundation.lp)
  files+=(emdash3_2_abelian_snake_exact_second_alpha_cover_object.lp)
  files+=(emdash3_2_abelian_snake_exact_second_alpha_cover_epi.lp)
  files+=(emdash3_2_abelian_snake_exact_second_alpha_cover_epic.lp)
  files+=(emdash3_2_abelian_snake_exact_second_alpha_cover_factor.lp)
  files+=(emdash3_2_abelian_snake_exact_second_beta_difference.lp)
  files+=(emdash3_2_abelian_snake_exact_second_kernel_factor.lp)
  files+=(emdash3_2_abelian_snake_exact_second_epsilon_paths.lp)
  files+=(emdash3_2_abelian_snake_exact_second_epsilon_factor.lp)
  files+=(emdash3_2_abelian_snake_exact_second_iota_comparison.lp)
  files+=(emdash3_2_abelian_snake_exact_second_cover_comparison.lp)
  files+=(emdash3_2_abelian_snake_exact_second_total_cover.lp)
  files+=(emdash3_2_abelian_snake_exact_second_cover_witness.lp)
  files+=(emdash3_2_abelian_snake_exact_second_result.lp)
  files+=(emdash3_2_exactness_extensions_foundation.lp)
  files+=(emdash3_2_exactness_extensions_to_exact_foundation.lp)
  files+=(emdash3_2_exactness_extensions_to_exact_extension.lp)
  files+=(emdash3_2_exactness_extensions_to_exact_zero.lp)
  files+=(emdash3_2_exactness_extensions_to_exact.lp)
  files+=(emdash3_2_abelian_canonical_kernel_extensions_foundation.lp)
  files+=(emdash3_2_abelian_canonical_kernel_extensions.lp)
  files+=(emdash3_2_abelian_snake_exact_third_pushout.lp)
  files+=(emdash3_2_abelian_snake_exact_third_zeta.lp)
  files+=(emdash3_2_abelian_snake_exact_third_zeta_epsilon.lp)
  files+=(emdash3_2_abelian_snake_exact_third_zeta_iota_to_su.lp)
  files+=(emdash3_2_abelian_snake_exact_third_su_path.lp)
  files+=(emdash3_2_abelian_snake_exact_third_zeta_zero.lp)
  files+=(emdash3_2_abelian_snake_exact_third_gamma_extension_foundation.lp)
  files+=(emdash3_2_abelian_snake_exact_third_gamma_extension_object.lp)
  files+=(emdash3_2_abelian_snake_exact_third_gamma_extension_monomorphism.lp)
  files+=(emdash3_2_abelian_snake_exact_third_gamma_extension_is_monic.lp)
  files+=(emdash3_2_abelian_snake_exact_third_gamma_extension_factor.lp)
  files+=(emdash3_2_abelian_snake_exact_third_gamma_extension_path.lp)
  files+=(emdash3_2_abelian_snake_exact_third_beta_difference.lp)
  files+=(emdash3_2_abelian_snake_exact_third_cokernel_factor.lp)
  files+=(emdash3_2_abelian_snake_exact_third_mu_reconstruction.lp)
  files+=(emdash3_2_abelian_snake_exact_third_difference_mu.lp)
  files+=(emdash3_2_abelian_snake_exact_third_pi_comparison.lp)
  files+=(emdash3_2_abelian_snake_exact_third_pi_epic.lp)
  files+=(emdash3_2_abelian_snake_exact_third_extension_comparison.lp)
  files+=(emdash3_2_abelian_snake_exact_third_extension_witness.lp)
  files+=(emdash3_2_abelian_snake_exact_third_result.lp)
  files+=(emdash3_2_abelian_snake_exact_fourth_foundation.lp)
  files+=(emdash3_2_abelian_snake_exact_fourth_extension.lp)
  files+=(emdash3_2_abelian_snake_exact_fourth_extension_projections.lp)
  files+=(emdash3_2_abelian_snake_exact_fourth_gamma_zero.lp)
  files+=(emdash3_2_abelian_snake_exact_fourth_cokernel_factor.lp)
  files+=(emdash3_2_abelian_snake_exact_fourth_comparison.lp)
  files+=(emdash3_2_abelian_snake_exact_fourth_result.lp)
  files+=(emdash3_2_abelian_snake_six_term_exact_pairs.lp)
  files+=(emdash3_2_abelian_snake_six_term_exact_data_intro.lp)
  files+=(emdash3_2_abelian_snake_six_term_exact_result_foundation.lp)
  files+=(emdash3_2_abelian_snake_six_term_exact_result_projections.lp)
  files+=(emdash3_2_abelian_snake_six_term_exact_pair_paths.lp)
  files+=(emdash3_2_abelian_snake_six_term_canonical_exactness.lp)
  files+=(emdash3_2_abelian_snake_six_term_exact_result.lp)
  files+=(emdash3_2_abelian_bimorphisms.lp)
  files+=(emdash3_2_iso_evidence_constructors.lp)
  files+=(emdash3_2_mono_epi_comparisons.lp)
  files+=(emdash3_2_cokernel_composite_comparison.lp)
  files+=(emdash3_2_cokernel_composite_pushout.lp)
  files+=(emdash3_2_cokernel_composite_monic.lp)
  files+=(emdash3_2_abelian_cokernel_composite_monic.lp)
  files+=(emdash3_2_homology_cokernel_inclusion.lp)
  files+=(emdash3_2_homology_cokernel_inclusion_monic.lp)
  files+=(emdash3_2_abelian_homology_cokernel_inclusion.lp)
  files+=(emdash3_2_hom_factor_spaces.lp)
  files+=(emdash3_2_hom_factor_cubical.lp)
  files+=(emdash3_2_hom_factor_source_isos.lp)
  files+=(emdash3_2_hom_factor_composition.lp)
  files+=(emdash3_2_hom_factor_views.lp)
  files+=(emdash3_2_hom_factor_epic_descent.lp)
  files+=(emdash3_2_cokernel_monic_factor_descent.lp)
  files+=(emdash3_2_iso_evidence_monic.lp)
  files+=(emdash3_2_kernel_maps.lp)
  files+=(emdash3_2_kernel_map_laws.lp)
  files+=(emdash3_2_kernel_map_isos.lp)
  files+=(emdash3_2_cokernel_maps.lp)
  files+=(emdash3_2_cokernel_map_laws.lp)
  files+=(emdash3_2_cokernel_map_isos.lp)
  files+=(emdash3_2_chain_pair_maps.lp)
  files+=(emdash3_2_chain_pair_cubical_maps.lp)
  files+=(emdash3_2_chain_pair_native_triangles.lp)
  files+=(emdash3_2_chain_pair_map_cycle_lifts.lp)
  files+=(emdash3_2_chain_pair_map_composition.lp)
  files+=(emdash3_2_homology_cycle_maps.lp)
  files+=(emdash3_2_homology_maps.lp)
  files+=(emdash3_2_homology_cycle_map_laws.lp)
  files+=(emdash3_2_homology_map_laws.lp)
  files+=(emdash3_2_homology_map_isos.lp)
  files+=(emdash3_2_chain_pair_map_snake.lp)
  files+=(emdash3_2_snake_row_comparisons.lp)
  files+=(emdash3_2_kernel_domain_comparison.lp)
  files+=(emdash3_2_iso_comparison_reconstruction.lp)
  files+=(emdash3_2_hom_factor_universality.lp)
  files+=(emdash3_2_short_exact_universal_records.lp)
  files+=(emdash3_2_homology_connecting_cover.lp)
  files+=(emdash3_2_homology_connecting_left_lift.lp)
  files+=(emdash3_2_homology_connecting_target_cycles.lp)
  files+=(emdash3_2_homology_connecting_cover_kernel.lp)
  files+=(emdash3_2_homology_connecting_cover_kernel_lift.lp)
  files+=(emdash3_2_homology_record_boundary_factors.lp)
  files+=(emdash3_2_homology_connecting_cover_kernel_boundary.lp)
  files+=(emdash3_2_homology_connecting_cycles_descent.lp)
  files+=(emdash3_2_homology_connecting_source_boundary_cover.lp)
  files+=(emdash3_2_homology_connecting_source_boundary_zero.lp)
  files+=(emdash3_2_homology_connecting_source_boundary_descent.lp)
  files+=(emdash3_2_homology_record_connecting.lp)
  files+=(emdash3_2_hom_factor_zero_descent.lp)
  files+=(emdash3_2_homology_record_cancellation.lp)
  files+=(emdash3_2_homology_family_map_factors.lp)
  files+=(emdash3_2_chain_pair_homology_actions.lp)
  files+=(emdash3_2_homology_connecting_projection_zero.lp)
  files+=(emdash3_2_homology_connecting_inclusion_zero.lp)
  files+=(emdash3_2_homology_window.lp)
  files+=(emdash3_2_homology_connecting_cover_quotient.lp)
  files+=(emdash3_2_homology_connecting_characterization.lp)
  files+=(emdash3_2_homology_boundary_naturality.lp)
  files+=(emdash3_2_cokernel_record_covers.lp)
  files+=(emdash3_2_homology_map_kernel_covers.lp)
  files+=(emdash3_2_homology_map_corrections.lp)
  files+=(emdash3_2_chain_pair_cycle_factors.lp)
  files+=(emdash3_2_homology_record_cycle_lifts.lp)
  files+=(emdash3_2_homology_first_exactness.lp)
  files+=(emdash3_2_homology_epic_covers.lp)
  files+=(emdash3_2_homology_second_exactness.lp)
  files+=(emdash3_2_homology_third_exactness.lp)
  files+=(emdash3_2_homology_exact_window.lp)
  files+=(emdash3_2_homology_exact_window_result.lp)
  files+=(emdash3_2_finite_arrow_tails.lp)
  files+=(emdash3_2_finite_arrow_tail_append.lp)
  files+=(emdash3_2_computational_exact_arrow_tails.lp)
  files+=(emdash3_2_short_exact_row_families.lp)
  files+=(emdash3_2_homology_window_families.lp)
  files+=(emdash3_2_homology_window_columns.lp)
  files+=(emdash3_2_homology_window_column_usability.lp)
  files+=(emdash3_2_homology_window_connecting_transformation.lp)
  files+=(emdash3_2_kernel_domain_comparison_factors.lp)
  files+=(emdash3_2_cokernel_codomain_comparison.lp)
  files+=(emdash3_2_snake_row_source_cycle_iso.lp)
  files+=(emdash3_2_snake_row_source_cycle_factor.lp)
  files+=(emdash3_2_snake_row_target_cokernel_iso.lp)
  files+=(emdash3_2_abelian_structure_elimination.lp)
  files+=(emdash3_2_abelian_snake_row_comparisons.lp)
  files+=(emdash3_2_short_exact_row_snake.lp)
  files+=(emdash3_2_short_exact_kernel_comparison.lp)
  files+=(emdash3_2_short_exact_cokernel_foundation.lp)
  files+=(emdash3_2_short_exact_cokernel_inverse_test.lp)
  files+=(emdash3_2_short_exact_cokernel_comparison.lp)
  files+=(emdash3_2_short_exact_rows.lp)
  files+=(emdash3_2_short_exact_row_chain_columns.lp)
  files+=(emdash3_2_hom_factor_chain_zero.lp)
  files+=(emdash3_2_short_exact_row_chain_projection.lp)
  files+=(emdash3_2_snake_row_source_compared_boundary.lp)
  files+=(emdash3_2_abelian_snake_second_postcomposition.lp)
  files+=(emdash3_2_snake_row_source_embedding_monic.lp)
  files+=(emdash3_2_snake_row_source_second_comparison.lp)
  files+=(emdash3_2_snake_row_source_upper_factor.lp)
  files+=(emdash3_2_snake_row_source_boundary_covered.lp)
  files+=(emdash3_2_snake_row_source_boundary_zero.lp)
  files+=(emdash3_2_snake_row_target_factors.lp)
  files+=(emdash3_2_snake_row_target_cycles.lp)
  files+=(emdash3_2_normal_mono_epic_factors.lp)
  files+=(emdash3_2_hom_factor_comparison_pasting.lp)
  files+=(emdash3_2_normal_mono_cycle_factors.lp)
  files+=(emdash3_2_cokernel_codomain_comparison_projection.lp)
  files+=(emdash3_2_snake_row_target_cokernel_projection.lp)
  files+=(emdash3_2_snake_row_target_homology_normal.lp)
  files+=(emdash3_2_snake_row_target_homology_factor.lp)
  files+=(emdash3_2_homology_connecting_factor.lp)
  files+=(emdash3_2_homology_connecting.lp)
  files+=(emdash3_2_kernel_short_exact_rows.lp)
  files+=(emdash3_2_selected_short_exact_rows.lp)
  files+=(emdash3_2_monic_image_comparison.lp)
  files+=(emdash3_2_short_exact_row_comparison_fibres.lp)
  files+=(emdash3_2_monic_selected_row_comparison.lp)
  files+=(emdash3_2_short_exact_normalization_foundation.lp)
  files+=(emdash3_2_short_exact_normalization_isos.lp)
  files+=(emdash3_2_short_exact_normalization_projections.lp)
  files+=(emdash3_2_short_exact_normalization.lp)
  files+=(emdash3_2_commutative_algebra_freyd_additive.lp)
  files+=(emdash3_2_commutative_algebra_freyd_cokernels.lp)
  files+=(emdash3_2_commutative_algebra_freyd_kernels.lp)
  files+=(emdash3_2_commutative_algebra_freyd_kernel_compatibility.lp)
  files+=(emdash3_2_commutative_algebra_freyd_selected_kernel_embedding.lp)
  files+=(emdash3_2_commutative_algebra_freyd_selected_kernel_lifting.lp)
  files+=(emdash3_2_commutative_algebra_freyd_selected_kernel_uniqueness.lp)
  files+=(emdash3_2_commutative_algebra_freyd_kernel_choices_from_weak_kernels.lp)
  files+=(emdash3_2_commutative_algebra_freyd_kernel_choice_providers.lp)
  files+=(emdash3_2_commutative_algebra_freyd_selected_homology.lp)
  files+=(emdash3_2_commutative_algebra_freyd_actual_homology.lp)
  files+=(emdash3_2_commutative_algebra_freyd_witnessed_preabelian.lp)
  files+=(emdash3_2_commutative_algebra_freyd_normal_monomorphisms.lp)
  files+=(emdash3_2_commutative_algebra_freyd_normal_epimorphisms.lp)
  files+=(emdash3_2_commutative_algebra_freyd_witnessed_abelian.lp)
  files+=(emdash3_2_commutative_algebra_freyd_snake_connecting.lp)
  files+=(emdash3_2_commutative_algebra_freyd_homology.lp)
  files+=(emdash3_2_commutative_algebra_freyd_functorial_homology.lp)
  files+=(emdash3_2_commutative_algebra_freyd_bounded_complexes.lp)
  files+=(emdash3_2_commutative_algebra_freyd_explicit_spines.lp)
  files+=(emdash3_2_commutative_algebra_freyd_explicit_epimorphisms.lp)
  files+=(emdash3_2_commutative_algebra_freyd_bounded_chain_maps.lp)
  files+=(emdash3_2_commutative_algebra_freyd_short_exact_rows.lp)
  files+=(emdash3_2_commutative_algebra_freyd_bounded_short_exact.lp)
  files+=(emdash3_2_commutative_algebra_freyd_images.lp)
  files+=(emdash3_2_gray_interchanger_orientation.lp)
  files+=(emdash3_2_gray_transformation_graph.lp)
  files+=(emdash3_2_gray_cubes.lp)
  files+=(emdash3_2_gray_transformation_graph_profile.lp)
  files+=(emdash3_2_gray_cube_decoder.lp)
  files+=(emdash3_2_gray_cube_dimension2.lp)
  files+=(emdash3_2_monads.lp)
  files+=(emdash3_2_triangular_binary_products.lp)
  files+=(emdash3_2_terminal_objects.lp)
  files+=(emdash3_2_cartesian_categories.lp)
  files+=(emdash3_2_triangular_binary_products_finite_limits.lp)
  files+=(emdash3_2_pullbacks.lp)
  files+=(emdash3_2_slice_dependent_products.lp)
  files+=(emdash3_2_checks.lp)
  files+=(emdash3_2_semisimplicial_face_codes.lp)
  files+=(emdash3_2_semisimplicial_index.lp)
  files+=(emdash3_2_simplex_shapes.lp)
  files+=(emdash3_2_coherent_nerve_levels.lp)
  files+=(emdash3_2_tetrahedron_faces.lp)
  files+=(emdash3_2_join_mapping_recursion.lp)
  files+=(emdash3_2_join_cross_compatibility.lp)
  files+=(emdash3_2_join_generator_compatibility.lp)
  files+=(emdash3_2_face_realization.lp)
  files+=(emdash3_2_dependent_simplex_bridge.lp)
  files+=(emdash3_2_dependent_simplex_path_associator.lp)
  files+=(emdash3_2_dependent_simplex_represented_source.lp)
  files+=(emdash3_2_dependent_simplex_native_dimensions.lp)
  files+=(emdash3_2_dependent_simplex_dimension4.lp)
  files+=(emdash3_2_dependent_simplex_codes.lp)
  files+=(emdash3_2_dependent_simplex_code_map.lp)
  files+=(emdash3_2_dependent_simplex_faces.lp)
  files+=(emdash3_2_shaped_pathout.lp)
  files+=(emdash3_2_pathout_transformation_reframing.lp)
  files+=(emdash3_2_pathout_transformation_lift.lp)
  files+=(emdash3_2_ordinal_join_pathout_successor.lp)
  files+=(emdash3_2_dependent_simplex_ordinal_adequacy.lp)
  files+=(emdash3_2_dependent_simplex_ordinal_filler.lp)
  files+=(emdash3_2_dependent_simplex_ordinal_dimension3.lp)
  files+=(emdash3_2_dependent_simplex_ordinal_dimension4.lp)
  files+=(emdash3_2_dependent_simplex_ordinal_recursive.lp)
  files+=(emdash3_2_prof_reindex_terminal_normalization.lp)
  files+=(emdash3_2_cubical_dependent_hom.lp)
  files+=(emdash3_2_cubical_square_total.lp)
  files+=(emdash3_2_cubical_internalization.lp)
  files+=(emdash3_2_cubical_arrow.lp)
  files+=(emdash3_2_cubical_arrow_composition.lp)
  files+=(emdash3_2_readable_pseudofunctors.lp)
  files+=(emdash3_2_cubical_arrow_functor.lp)
  files+=(emdash3_2_cubical_square_level.lp)
  files+=(emdash3_2_cubical_levels.lp)
  files+=(emdash3_2_semicubical_face_codes.lp)
  files+=(emdash3_2_semicubical_index.lp)
  files+=(emdash3_2_semicubical_face_action.lp)
  files+=(emdash3_2_semicubical_nerve.lp)
  files+=(emdash3_2_semicubical_frames.lp)
  files+=(emdash3_2_semicubical_representables.lp)
  files+=(emdash3_2_cubical.lp)
  files+=(emdash3_2_cubical_yoneda.lp)
  files+=(emdash3_2_semisimplicial_diagrams.lp)
  files+=(emdash3_2_simplex2_sieves.lp)
  files+=(emdash3_2_path_groupoid_2horn_fillers.lp)
  files+=(emdash3_2_semisimplicial_decalage.lp)
  files+=(emdash3_2_finite_limits.lp)
  files+=(emdash3_2_direct_cover_questions.lp)
  files+=(emdash3_2_direct_cover_question_families.lp)
  files+=(emdash3_2_direct_cover_algebras.lp)
  files+=(emdash3_2_direct_cover_internal_sheaves.lp)
  files+=(emdash3_2_direct_cover_completion_hit.lp)
  files+=(emdash3_2_direct_cover_completion_eliminator.lp)
  files+=(emdash3_2_groupoidification_hit.lp)
  files+=(emdash3_2_groupoidification_universality.lp)
  files+=(emdash3_2_set_path_pointwise_transformation.lp)
  files+=(emdash3_2_groupoidification_set_extensionality.lp)
  files+=(emdash3_2_groupoidification_composition.lp)
  files+=(emdash3_2_groupoidification_interval_recovery.lp)
  files+=(emdash3_2_commutative_algebra_scheme_chart_overlaps.lp)
  files+=(emdash3_2_commutative_algebra_laurent.lp)
  files+=(emdash3_2_commutative_algebra_scheme_laurent_overlaps.lp)
  files+=(emdash3_2_commutative_algebra_projective_line.lp)
fi

for file in "${files[@]}"; do
  check_file "$file"
done
